services:
  postgres:
    image: postgis/postgis:17-master
    platform: linux/amd64
    environment:
      POSTGRES_DB: safe_zone_db
      POSTGRES_USER: safezone_user
      POSTGRES_PASSWORD: safezone_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
